sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilgupta1112/docker-react -f Dokcerfile.dev .

script:
  - docker run nikhilgupta1112/docker-react npm  run test -- --coverage