sudo: required
services:
  - docker

before_install:
  - docker build -t nikhilgupta1112/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikhilgupta1112/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-792433786172"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret-access_key: $AWS_SECRET_KEY